### ISSUE TITLE
Configure/Release

### ISSUE THREAD

**Issue by teburd** [imxrt-rs/imxrt-hal#20]
Configuring a peripheral should be undoable in some way to return it back to its default state.

The C SDK does this using _init/_deinit pairs for peripherals, we can probably do this using type states and similar calls, instead perhaps using configure/release as the call pair.

**Comment by bfrog** [comment]
Really we are doing clock, so perhaps unclock is the right term to use here anyways

**Comment by bfrog** [comment]
There's really a few possible States a peripheral may be in beyond clocked, but the goal is the same, a reversal of the peripheral states from Unclocked -> Clocked -> Configured and back
